### ISSUE TITLE
ARM Mode

### ISSUE THREAD

**Issue by oblivia-simplex** [ekse/unicorn-rs#12]
Hey, thanks for doing this. It's a really useful project. 
Is there a reason why ```UC_MODE_ARM``` isn't available as a Mode argument? It looks like it's been commented out in the enum listing. There seems to be a workaround -- just use ```LITTLE_ENDIAN``` as the mode argument -- but this seems unnecessarily convoluted. Maybe it would be better to just have modes as integer values, identified by global, static variables? Or strings that are translated by a hashtable into the integer/C-enum arguments needed by the engine?

**Comment by ekse** [comment]
Hi Oblivia.

Thank you for your comment, this is really appreciated! 

The reason some of the modes are commented out is that Rust does not support having multiple entries in an enum with the same value. It is unfortunate that unicorn has those. Still an enum is usually better than plain integer values as it is treated as a type and will give a compile error if you try to pass the wrong enum. When using constants, if you pass the parameters in the wrong order in, say `new(arch: Arch, mode: Mode)` it will compile just fine but obviously won't do what you wanted. The same would be true for strings.

If you want to use the commented constants, a workaround would be to add something like this to your project. It's a bit ugly as Rust does not support casts from integers to enums (again for type safety), but it will contain the uglyness to a single line. You can then use the constant as you normally would. 
 
```rust
    let MODE_ARM = unsafe {mem::transmute::<u32, unicorn::Mode>(0)};
    let mut emu = CpuARM::new(MODE_ARM).expect("failed to instantiate emulator");
```

**Comment by oblivia-simplex** [comment]
That does clear things up. Thanks!
