### ISSUE TITLE
Accessing the CPU in hooks

### ISSUE THREAD

**Issue by oblivia-simplex** [ekse/unicorn-rs#13]
disclaimer: I'm a rust noob. I may be missing something essential, here.

Is there an intended way to access the Unicorn engine's CPU context from a code hook? The following (which more or less follows the pattern in the test routines) compiles without complaint, but then causes the emulation to hang for several seconds, until it crashes with an exit code of 1. 
```
 53     if _DEBUG {                                                                                                                              
 54       let callback_c =                                                                                                                       
 55         move |u: &unicorn::Unicorn, addr: u64, _: u32| {                                                                                     
 56           println!("[{:08x}] SP: {:08x}", addr, u.reg_read(RegisterARM::SP.to_i32()).expect("Error reading SP"));                            
 57         };                                                                                                                                   
 58       // add some hooks if in debugging mode                                                                                                 
 59       uc.add_code_hook(CodeHookType::CODE,                                                                                                   
 60                        BASE_ADDR,                                                                                                            
 61                        BASE_ADDR+(MEM_SIZE as u64),                                                                                          
 62                        callback_c)                                                                                                           
 63         .expect("Error adding code hook");                                                                                                   
 64     }                                                                                                                                        
 65                                                                                                                                              
 66     uc                                                                                                                                       
 67   }         
```
edit: what I'm trying to do here is access the internal unicorn handle's reg_read() method, in lieu of the usual CPU reg_read wrapper (which takes an enum arg instead of an i32), since the Unicorn handle is all that the callback signature seems to give us to work with. This same hook works fine if I leave out the u.reg_read bit, and just print the addr value.

**update**: No worries. Turned out to be a scoping/lifetime issue after all, which, for reasons still unclear to me, the compiler wasn't picking up on. I moved the hook-adding routine to a separate function -- outside of the function that creates and initializes the engine -- and then called that function from the function that calls the first, initializing function, and **now everything appears to be working fine**. This _partially_ makes sense to me, given what I grasp of rust's memory management system, and the rest I suppose will become clearer as I become less noobish. Closing the issue. Thanks for letting me rubber-duck debug here.

**Comment by isra17** [comment]
This look like a guenine issue, either the compiler should pick up the lifetime issue or it should not crash. Are you able to get a simple test case that reliably reproduce the issue?
Thanks!

**Comment by isra17** [comment]
Got it! Need to Box the callback otherwise Rust might allocate them on the stack...
Test case here: https://github.com/isra17/unicorn-rs/commit/5cb2c4e3b1ead87231ebe245ef97ad56f6d909b1

**Comment by isra17** [comment]
Disregard last comment, crash come from the Unicorn object pointer being first saved in the callback data. The pointer however is first stored on the init function stack. Returning the object from the function move the value to the parent fram and invalidate the saved pointer. I think this can be fixed by forcing `Box<Self>` on `self` in `add_*_hook` functions.

**Comment by oblivia-simplex** [comment]
Hey, just catching up with this thread now. Glad to hear I stumbled on a worthwhile bug. I'll pull the fix, and see if I get better mileage out of it. Thanks.
