### ISSUE TITLE
Possible to bind uc_mem_map_ptr?

### ISSUE THREAD

**Issue by petmac** [ekse/unicorn-rs#27]
Is it possible to bind `uc_mem_map_ptr`, thereby allowing the user to provide their own memory? Maybe this isn't reasonably to do with Rust, I don't know it well enough.

**Comment by ekse** [comment]
I think it should be possible. Do you have an idea what kind of memory buffer you would like to use? I want to be sure the implementation I come up with is working in your use-case.

**Comment by petmac** [comment]
It's for a multithreaded [emulator](https://github.com/Vita3K/Vita3K), I was debating whether a rewrite in Rust is feasible.

Currently a 4GB address space is reserved using `mmap` on macOS and `VirtualAlloc` on Windows and pages get committed as required.

That address space pointer is passed to multiple Unicorn instances using `uc_mem_map_ptr`.

**Comment by ekse** [comment]
That's a pretty cool project! I pushed a branch with mem_map_ptr support added (see #28). `ptr` is passed as a pointer to the buffer, the type is generic (`*mut T`) so I think it should be useable with pretty much any type of memory. I added a test that shows how to use use an array or a Vec as examples.

I think that should work for your use case?

**Comment by petmac** [comment]
Thank you. I'm new to Rust so I can't say for sure, but I imagine as long as I can get that pointer from `mmap` and ownership isn't taken away from the caller, it should be good.

Thank you for looking into this!

**Comment by ekse** [comment]
I decided to make `mem_map_ptr()` unsafe,. If someone calls this function with a value of `size` that does not match unicorn will probably crash. There is nothing wrong with using mem_map_ptr and it doesn't change anything from a user perspective other than having to wrap the call inside an unsafe{} block.

I will go ahead and merge this change, I will also do an update of the package on crates.io.

**Comment by ekse** [comment]
The package has been update to 0.8.0.
