### ISSUE TITLE
"improper_ctypes" Build warning

### ISSUE THREAD

**Issue by isra17** [ekse/unicorn-rs#5]
Complete warning:
```
src/ffi.rs:37:36: 37:59 warning: found non-foreign-function-safe member in struct marked #[repr(C)]: found struct without foreign-function-safe representation annotation in foreign module, consider adding a #[repr(C)] attribute to the type, #[warn(improper_ctypes)] on by default
src/ffi.rs:37                           regions: *const *const MemRegion,
                                                 ^~~~~~~~~~~~~~~~~~~~~~~
```

Seems to come from the `Protection` bitflags that doesn't take the `#[repr(C)]` attribute as expected. I've got https://github.com/isra17/unicorn-rs/commit/3eae40b378928a4a1c09932e7706892ec0cd92da that you might want to cherry-pick.

**Comment by ekse** [comment]
Thanks, fixed with https://github.com/ekse/unicorn-rs/commit/fec8356b39f2d90e642abd0567ae8e3a7e9d64b4.
