### ISSUE TITLE
Fork for UnicornAFL / Autogenerate bindings?

### ISSUE THREAD

**Issue by domenukk** [ekse/unicorn-rs#68]
I just wanted to point out I have taken your code and started to integrate the bindings into my AFL fork of unicorn. 
To keep overhead low (and my sanity), I moved the bindings into the main repo.
https://github.com/domenukk/unicorn/tree/rust/bindings/rust
The changes itself can be found here
https://github.com/ekse/unicorn-rs/compare/master...domenukk:unicornafl
Specifically, I have added rust to `./const_generator.py` as I constantly (heh) add consts, see:
https://github.com/domenukk/unicorn/blob/rust/bindings/const_generator.py
Maybe auto generating constants could be interesting for this project, too.

A thing I changed to be able to autogenerate them is to add aliases for ENUM types that are used more than once, see
https://github.com/domenukk/unicorn-rs/blob/15e2e00a46bead6c8fea7137ad53f2a9755fa110/libunicorn-sys/src/mips_const.rs#L205

I'm open to discussions of all sorts. :)
Keep up the good work.

**Comment by ekse** [comment]
Hi domenukk,

This looks like a cool project. Unfortunately I don't have much time to work on unicorn-rs anymore.

How do you use the bindings with your configuration? Do you reference them by path?

**Comment by domenukk** [comment]
Right now by path, yes. Although this is likely not the best solution. We'll see. I'm open for suggestions. Maybe even releasing an additional crate might be an option at some point.
Too bad you're short on time but we all know there are only so many hours in the day.
Anyway if you have additional suggestions or something I can do for unicorn-rs, feel free to reach out. Thanks for the work that went into this project up to this point.
