### ISSUE TITLE
I want to find a maintainer

### ISSUE THREAD

**Issue by lzutao** [ekse/unicorn-rs#69]
Hi @ekse , I would like to find another maintainer. In the meantime, you could
handle the ownership of this crate to me. At least I could merge the bug fix PR
if there are any.

If you want direct conversation, look for me on Rust Discord (@lzutao).

**Comment by ekse** [comment]
Thank you for the offer. I'm unable to message you on Discord, it says you don't accept direct messages.

As I see you are already a maintainer of the goblin crate, I will add you as a maintainer.

**Comment by lzutao** [comment]
Could you send me a friend request first?

**Comment by ekse** [comment]
It says you don't accept friend requests either, you try adding me my username is Sébastien Duquette
#1335

**Comment by lzutao** [comment]
Weird. I cannot find you. My username is `lzutao#3887`.

**Comment by lzutao** [comment]
Have you joined the Rust Discord server?

**Comment by lzutao** [comment]
My current settings are fine:
![image](https://user-images.githubusercontent.com/15225902/81414678-8c560100-9171-11ea-93e3-84a99736770e.png)

**Comment by ekse** [comment]
lol what is going on, I'm on the Rust discord server.. Anyways, I sent you invite both on github and on crates.io.

**Comment by lzutao** [comment]
Thanks. Could you comment in `#rust-usage` channel? Maybe we can talk there.

**Comment by ekse** [comment]
I talked with @lzutao, I added him as a maintainer of the crate and owner of the repository on github.
